import React from 'react';
import { Link, useParams, Navigate } from 'react-router-dom';
import { ArrowLeft, ShieldAlert, ScrollText, Lock } from 'lucide-react';
import Navbar from '../components/common/Navbar';
import Footer from '../components/common/Footer';

/*
 * Legal — Terms of Service, Privacy Policy, and Legal Disclaimer.
 *
 * These three were shipping as href="#" in the footer of a product that gives
 * people legal information. The disclaimer in particular is not optional:
 * under Bar Council of India rules this platform must be unambiguous that it
 * is not a law firm and creates no advocate-client relationship.
 */

const LAST_UPDATED = '26 August 2026';

const DOCS = {
  disclaimer: {
    icon: ShieldAlert,
    eyebrow: 'Read this first',
    title: 'Legal Disclaimer',
    lede:
      'NYAAY AI is a legal information tool. It is not a lawyer, and nothing it produces is legal advice.',
    body: [
      {
        h: 'We are not a law firm',
        p: [
          'NYAAY AI is not a law firm, is not a registered legal practitioner, and is not enrolled with any State Bar Council or with the Bar Council of India. Using this platform does not create an advocate-client relationship between you and NYAAY AI, its authors, or its contributors.',
          'No communication you have with this platform is privileged. Do not send us anything you would not be willing to disclose.',
        ],
      },
      {
        h: 'Output is generated by a language model and can be wrong',
        p: [
          'Every dossier, draft, checklist, and answer on this platform is produced by an AI system that retrieves text from a corpus of Indian Bare Acts and then generates prose from it. That process reduces invented citations but does not eliminate error. The system can misread your facts, cite a provision that does not apply to your situation, miss a provision that does, or rely on a version of a statute that has since been amended.',
          'Statutory references, limitation periods, fee amounts, and forum names should be independently verified against the current official text before you rely on them.',
        ],
      },
      {
        h: 'Not a substitute for an advocate',
        p: [
          'Indian law is jurisdiction-specific and fact-specific. Identical facts can produce different outcomes across states, tribunals, and benches. If your matter involves a limitation deadline, a criminal allegation, a court appearance, custody of a child, or anything where you could lose money, liberty, or property, consult a licensed advocate.',
          'If you cannot afford one, you have a statutory right to free legal aid under the Legal Services Authorities Act, 1987. Contact your District Legal Services Authority (DLSA), your State Legal Services Authority (SLSA), or call the NALSA helpline on 15100.',
        ],
      },
      {
        h: 'Drafts are templates, not filings',
        p: [
          'Documents this platform generates — RTI applications, first appeals, reply notices, complaints — are unsigned drafts containing placeholder fields in square brackets. They have not been reviewed by a legal practitioner. You are responsible for checking the facts, completing every placeholder, confirming the correct addressee and forum, and meeting the applicable filing requirements before you sign or submit anything.',
        ],
      },
      {
        h: 'Limitation of liability',
        p: [
          'This platform is provided on an "as is" and "as available" basis, without warranty of any kind, express or implied. To the fullest extent permitted by law, NYAAY AI and its contributors accept no liability for any loss, damage, cost, penalty, adverse order, or missed deadline arising from your use of, or reliance on, anything this platform produces.',
          'You use it at your own risk, and you remain solely responsible for every decision you take.',
        ],
      },
      {
        h: 'Status of this project',
        p: [
          'NYAAY AI was built for the OOSC 4.0 open-source challenge and is a working prototype, not a commercial service. It carries no uptime guarantee, no support obligation, and no commitment to preserve your data. Treat it as a research demonstration.',
        ],
      },
    ],
  },

  terms: {
    icon: ScrollText,
    eyebrow: 'Terms',
    title: 'Terms of Service',
    lede:
      'The rules for using NYAAY AI. By creating an account or submitting a query, you accept these terms.',
    body: [
      {
        h: 'Who may use this platform',
        p: [
          'You must be at least 18 years old, or using the platform under the supervision of a parent or guardian who accepts these terms on your behalf. You must provide accurate information when you create an account and keep your credentials secure. You are responsible for activity carried out under your account.',
        ],
      },
      {
        h: 'What you may use it for',
        p: [
          'You may use NYAAY AI to understand your own civic or legal situation, to learn what Indian statutes say, and to generate draft documents for your own use.',
        ],
      },
      {
        h: 'What you may not do',
        p: [
          'You may not use this platform to practise law or hold yourself out as qualified to do so; to generate documents you will present as having been prepared or reviewed by an advocate; to harass, defame, or bring vexatious proceedings against another person; to submit another person\'s personal data without a lawful basis; to attempt to extract, scrape, or reconstruct the underlying model or corpus at scale; or to interfere with the platform\'s operation or security.',
        ],
      },
      {
        h: 'Your content',
        p: [
          'You keep ownership of the facts and documents you submit. You grant us a limited, revocable licence to process them for the sole purpose of generating your response. We do not sell your content and we do not use it to advertise to you.',
        ],
      },
      {
        h: 'Availability and changes',
        p: [
          'This is a prototype. Features may change or be withdrawn, and the service may be unavailable without notice. We may update these terms; material changes will be reflected in the "last updated" date below. Continuing to use the platform after a change means you accept the revised terms.',
        ],
      },
      {
        h: 'Termination',
        p: [
          'You may stop using the platform and request deletion of your account at any time. We may suspend or terminate access where these terms have been breached, or where continued operation would be unlawful or unsafe.',
        ],
      },
      {
        h: 'Governing law',
        p: [
          'These terms are governed by the laws of India. Nothing here limits any right you have as a consumer under the Consumer Protection Act, 2019, or any other right that cannot lawfully be excluded.',
        ],
      },
      {
        h: 'No legal advice',
        p: [
          'These terms operate alongside our Legal Disclaimer, which explains in full why this platform does not give legal advice. If the two conflict on that question, the Legal Disclaimer prevails.',
        ],
      },
    ],
  },

  privacy: {
    icon: Lock,
    eyebrow: 'Privacy',
    title: 'Privacy Policy',
    lede:
      'What we collect, why, and what you can do about it. Legal queries are sensitive, so this is deliberately narrow.',
    body: [
      {
        h: 'What we collect',
        p: [
          'Account data: your email address and, if you provide one, a display name. Authentication is handled by Google Firebase Authentication; we never see or store your password.',
          'Query data: the text of the civic or legal problem you describe, any documents you upload, and the dossiers and drafts generated in response. This is stored so you can return to your saved cases.',
          'Technical data: basic request logs needed to operate and debug the service.',
        ],
      },
      {
        h: 'What we do not collect',
        p: [
          'We do not ask for your Aadhaar number, PAN, bank details, or government ID. If a generated draft references such a document, the platform inserts a bracketed placeholder for you to complete offline — that value is not sent to us. We do not run advertising and we do not sell or rent your data to anyone.',
        ],
      },
      {
        h: 'Sensitive personal data',
        p: [
          'A legal query can reveal caste, religion, health, sexual orientation, financial distress, or involvement in proceedings. Under the Digital Personal Data Protection Act, 2023 this deserves particular care. Please include only the facts needed to answer your question, and avoid naming third parties where you can describe them by role instead ("my landlord", "the service centre").',
        ],
      },
      {
        h: 'Who processes your data',
        p: [
          'Google Firebase — authentication and database hosting. A third-party large language model provider — generates the dossier text from your query. Documents you upload are processed to extract text and are not used to train any model. We do not transfer your data to anyone else except where compelled by law.',
        ],
      },
      {
        h: 'How long we keep it',
        p: [
          'Saved cases persist until you delete them or delete your account. Deleting a case removes it from your account. Because this is a prototype, backups may lag deletion by a short period.',
        ],
      },
      {
        h: 'Your rights',
        p: [
          'You may ask us to show you the data we hold about you, correct it, delete it, or export it. You may withdraw consent and close your account at any time. To exercise any of these, raise an issue on the project repository linked in the footer.',
        ],
      },
      {
        h: 'Security, honestly stated',
        p: [
          'Data is transmitted over TLS and stored in managed Google infrastructure. This is a hackathon prototype and has not undergone an independent security audit. Please do not upload documents whose disclosure would seriously harm you.',
        ],
      },
    ],
  },
};

export default function Legal() {
  const { doc } = useParams();
  const entry = DOCS[doc];

  if (!entry) {
    return <Navigate to="/legal/disclaimer" replace />;
  }

  const Icon = entry.icon;

  return (
    <div className="min-h-screen bg-paper text-ink flex flex-col font-sans">
      <Navbar />

      {/* Navbar is 64px, plus a ~46px nav strip below lg. */}
      <main className="flex-grow pt-[124px] lg:pt-[88px]">
        {/* Header */}
        <header className="border-b border-rule bg-paper-sunken">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
            <Link
              to="/"
              className="inline-flex items-center gap-1.5 text-[13px] font-medium text-accent-text hover:text-accent-deep transition-colors mb-8 rounded focus-visible:ring-2 focus-visible:ring-accent focus-visible:outline-none"
            >
              <ArrowLeft aria-hidden="true" className="w-3.5 h-3.5" />
              Back to NYAAY AI
            </Link>

            <div className="flex items-center gap-2 mb-3">
              <Icon aria-hidden="true" className="w-4 h-4 text-accent" />
              <span className="text-[12px] font-semibold uppercase tracking-[0.08em] text-accent-text">
                {entry.eyebrow}
              </span>
            </div>

            <h1 className="font-serif text-display-lg font-bold text-ink">
              {entry.title}
            </h1>

            <p className="mt-4 text-lg text-ink-secondary leading-relaxed max-w-2xl">
              {entry.lede}
            </p>

            <p className="mt-6 text-xs text-ink-tertiary">
              Last updated {LAST_UPDATED}
            </p>
          </div>
        </header>

        {/* Body */}
        <article className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
          <div className="space-y-10">
            {entry.body.map((section, i) => (
              <section key={section.h} className="space-y-3">
                <div className="flex items-baseline gap-3">
                  <span className="text-xs text-accent-text font-bold shrink-0 pt-1.5">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <h2 className="font-serif text-heading font-bold text-ink">
                    {section.h}
                  </h2>
                </div>
                <div className="pl-0 sm:pl-9 space-y-3">
                  {section.p.map((para, j) => (
                    <p key={j} className="text-[15px] text-ink-secondary leading-relaxed">
                      {para}
                    </p>
                  ))}
                </div>
              </section>
            ))}
          </div>

          {/* Cross-links */}
          <nav
            className="mt-16 pt-8 border-t border-rule flex flex-wrap gap-x-6 gap-y-2 text-[13px]"
            aria-label="Other legal documents"
          >
            {Object.entries(DOCS)
              .filter(([key]) => key !== doc)
              .map(([key, value]) => (
                <Link
                  key={key}
                  to={`/legal/${key}`}
                  className="font-medium text-accent-text hover:text-accent-deep transition-colors rounded focus-visible:ring-2 focus-visible:ring-accent focus-visible:outline-none"
                >
                  {value.title} →
                </Link>
              ))}
          </nav>

          {/* Legal aid callout — the genuinely useful thing on this page */}
          <aside className="mt-10 p-5 bg-paper-sunken border-l-2 border-accent rounded-[2px]">
            <h2 className="font-serif text-base font-bold text-ink">
              Need a real lawyer and cannot afford one?
            </h2>
            <p className="mt-2 text-[14px] text-ink-secondary leading-relaxed">
              Free legal aid is a statutory right under the Legal Services Authorities Act, 1987.
              Call the NALSA helpline on{' '}
              <a
                href="tel:15100"
                className="font-bold text-accent-text hover:text-accent-deep underline decoration-dotted"
              >
                15100
              </a>{' '}
              or approach your District Legal Services Authority.
            </p>
          </aside>
        </article>
      </main>

      <Footer />
    </div>
  );
}
